### PR TITLE
CryoChip

### PR DESCRIPTION
**Pull request by joerdsonsilva**

### CODE REVIEW

**Comment by KrzysztofHerman** [comment]
We are reviewing the submissions. I will be back with our observations here. Anyway there is still a headroom for improvements.

**Comment by KrzysztofHerman** [comment]
@joerdsonsilva 

After the revision we would like to ask you to provide some documentation and background of your project, 

Although the design is DRC clean it have a lot of LVS issues, are you aware of that ? Will it be fixed ?

**Comment by joerdsonsilva** [comment]
The project documentation has been added. Yes, the LVS issues will be fixed. The LVS before the Fill is clean, but the LVS after the Fill is showing some errors. An issue will be opened regarding this matter. We have any room for gds modification?

**Comment by KrzysztofHerman** [comment]
@joerdsonsilva @britovski please update your GDS fixing contact sizes in the last row (3-rd and 4-th) column. Now it is too big. The correct size is `0.16x0.16` um

**Comment by KrzysztofHerman** [comment]
image

**Comment by joerdsonsilva** [comment]
updated as requested. The errors presented in the PR DRC are from AFil.g2 and M1-5Fil.h, is this normal behavior at this stage?

**Comment by KrzysztofHerman** [comment]
@joerdsonsilva @britovski 

Congratulations your design was accepted for production
File name: FMD_QNC_CryoChip_4.gds
Top cell name: CryoChip
Testfield: T576

I had to remove the logo because of critical DRC issues.

**Pull request merged**
